# Generated by Django 6.0.3 on 2026-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguido_por', models.CharField(max_length=100, verbose_name='Quien lo sigue/llamador')),
                ('origen', models.CharField(choices=[('Redes', 'Redes Sociales'), ('Evento', 'Evento'), ('Referido', 'Referido'), ('Difusion', 'Acción de Difusión')], max_length=50)),
                ('referente', models.CharField(blank=True, max_length=100, null=True)),
                ('segmentacion', models.CharField(blank=True, max_length=100)),
                ('trato', models.CharField(choices=[('Sr', 'Sr.'), ('Sra', 'Sra.'), ('Sres', 'Sres.')], max_length=10)),
                ('genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('empresa', models.CharField(blank=True, max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=150)),
                ('celular', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('tipo_donante', models.CharField(choices=[('Recurrente', 'Recurrente'), ('Eventual', 'Eventual')], max_length=20)),
                ('monto_mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha_alta', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
