# Generated by Django 6.0.3 on 2026-03-13 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField()),
                ('metodo', models.CharField(choices=[('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Otro', 'Otro')], max_length=50)),
                ('comprobante', models.CharField(blank=True, help_text='Nro de operación o referencia', max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='fundacion_app.donante')),
            ],
        ),
    ]
