# Generated by Django 6.0.3 on 2026-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion_app', '0002_donacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='tipo_donante',
            field=models.CharField(choices=[('Recurrente', 'Recurrente'), ('Eventual', 'Eventual'), ('UnicaVez', 'Única Vez')], max_length=20),
        ),
    ]
