# Generated by Django 6.0.3 on 2026-03-16 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion_app', '0003_alter_donante_tipo_donante'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('F', 'Fijo'), ('V', 'Variable')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagado', models.BooleanField(default=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='gastos/comprobantes/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundacion_app.categoriagasto')),
            ],
        ),
    ]
