# Generated by Django 6.0.3 on 2026-03-31 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion_app', '0004_categoriagasto_gasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hogares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contacto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Otro', 'Otro')], default='Transferencia', max_length=50)),
                ('pagado', models.BooleanField(default=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='cashflow/comprobantes/')),
                ('notas', models.TextField(blank=True)),
                ('gasto_origen_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fundacion_app.categoriagasto')),
                ('hogar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='fundacion_app.hogares')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
