# Generated by Django 6.0.3 on 2026-03-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundacion_app', '0008_alter_hogares_contacto_alter_hogares_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriagasto',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], default='egreso', max_length=10),
        ),
        migrations.AlterField(
            model_name='categoriagasto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('F', 'Fijo'), ('V', 'Variable')], max_length=50),
        ),
    ]
